### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by ftlong6666** [lim-anggun/FgSegNet_v2#14]
Hello how to evaluate the result of the method in CDnet 2014 dataset? I follow your links and tried to follow everything but I got this error.

```
The file C:\dataset\badWeather\blizzard\stats.txt doesn't exist.
It means there was an error calling the comparator.
Traceback (most recent call last):
  File "modified_process_folder.py", line 129, in <module>
    main()
  File "modified_process_folder.py", line 46, in main
    processFolder(datasetPath, binaryRootPath)
  File "modified_process_folder.py", line 62, in processFolder
    confusionMatrix = compareWithGroungtruth(videoPath, binaryPath)  #STATS
  File "modified_process_folder.py", line 84, in compareWithGroungtruth
    return readCMFile(statFilePath)
  File "modified_process_folder.py", line 90, in readCMFile
    raise Exception('error')
Exception: error
```
Should we recompile the comparator?, but in original file comparator.exe is exist.

**Comment by lim-anggun** [comment]
hi @ftlong6666,
Make you that read the README file for the instruction.
And make sure that you use python3 and the directory is writable.
Above error said that the `stats.txt` doesn't exist. This means that it cannot be created inside the blizzard directory.
