### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by HuaYangCheng** [lim-anggun/FgSegNet_v2#18]
The log is as follows:

Using TensorFlow backend.

->>> intermittentObjectMotion / abandonedBox
Traceback (most recent call last):
  File "extract_mask.py", line 205, in <module>
    img = kImage.load_img(ROI_file, grayscale=True)
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 322, in load_img
    img = pil_image.open(path)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'CDnet2014_dataset/intermittentObjectMotion/abandonedBox/ROI.bmp'

**Comment by Akhilesh64** [comment]
@hycheng345188780 cross-check whether the ROI.bmp file is present in the 'CDnet2014_dataset/intermittentObjectMotion/abandonedBox' directory. The error specifies so.
